from sqlalchemy import Column, Integer, String, Boolean, JSON, ForeignKey
from auth.db import Base

class User_Profile(Base):
    __tablename__ = "user_profile"

    id = Column(Integer, primary_key=True, autoincrement=True)
    github_id = Column(Integer, unique=True, index=True)
    user_id = Column(String, ForeignKey("user.id"))


    login = Column(String)
    node_id = Column(String)
    avatar_url = Column(String)
    gravatar_id = Column(String)
    url = Column(String)
    html_url = Column(String)
    followers_url = Column(String)
    following_url = Column(String)
    gists_url = Column(String)
    starred_url = Column(String)
    subscriptions_url = Column(String)
    organizations_url = Column(String)
    repos_url = Column(String)
    events_url = Column(String)
    received_events_url = Column(String)
    type = Column(String)
    user_view_type = Column(String)
    site_admin = Column(Boolean)
    name = Column(String)
    company = Column(String, nullable=True)
    blog = Column(String)
    location = Column(String, nullable=True)
    email = Column(String, nullable=True)
    hireable = Column(Boolean, nullable=True)
    bio = Column(String, nullable=True)
    twitter_username = Column(String, nullable=True)
    notification_email = Column(String, nullable=True)
    public_repos = Column(Integer)
    public_gists = Column(Integer)
    followers = Column(Integer)
    following = Column(Integer)
    created_at = Column(String)
    updated_at = Column(String)
    private_gists = Column(Integer)
    total_private_repos = Column(Integer)
    owned_private_repos = Column(Integer)
    disk_usage = Column(Integer)
    collaborators = Column(Integer)
    two_factor_authentication = Column(Boolean)
    plan = Column(JSON)
