"""Initial migration

Revision ID: 2e3deec81534
Revises: 50f9cfa58402
Create Date: 2025-05-04 17:21:21.778308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3deec81534'
down_revision: Union[str, None] = '50f9cfa58402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchased_animals_animal_id', table_name='purchased_animals')
    op.drop_index('ix_purchased_animals_id', table_name='purchased_animals')
    op.drop_index('ix_purchased_animals_user_id', table_name='purchased_animals')
    op.drop_table('purchased_animals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchased_animals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('animal_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('purchase_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchased_animals_user_id', 'purchased_animals', ['user_id'], unique=False)
    op.create_index('ix_purchased_animals_id', 'purchased_animals', ['id'], unique=False)
    op.create_index('ix_purchased_animals_animal_id', 'purchased_animals', ['animal_id'], unique=False)
    # ### end Alembic commands ###
