"""add  field in app2/models

Revision ID: 47e4185c0efa
Revises: ccd562a06e05
Create Date: 2025-03-24 02:57:52.552348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e4185c0efa'
down_revision: Union[str, None] = 'ccd562a06e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchased_animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchased_animals_animal_id'), 'purchased_animals', ['animal_id'], unique=False)
    op.create_index(op.f('ix_purchased_animals_id'), 'purchased_animals', ['id'], unique=False)
    op.create_index(op.f('ix_purchased_animals_user_id'), 'purchased_animals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchased_animals_user_id'), table_name='purchased_animals')
    op.drop_index(op.f('ix_purchased_animals_id'), table_name='purchased_animals')
    op.drop_index(op.f('ix_purchased_animals_animal_id'), table_name='purchased_animals')
    op.drop_table('purchased_animals')
    # ### end Alembic commands ###
