"""Initial migration

Revision ID: 48fe509d46fe
Revises: 
Create Date: 2025-03-21 03:39:48.753567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fe509d46fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_animals_id', table_name='animals')
    op.drop_index('ix_animals_name', table_name='animals')
    op.drop_index('ix_animals_species', table_name='animals')
    op.drop_index('ix_animals_xxx', table_name='animals')
    op.drop_index('ix_animals_yyy', table_name='animals')
    op.drop_table('animals')
    op.drop_index('ix_localstocks_id', table_name='localstocks')
    op.drop_index('ix_localstocks_name', table_name='localstocks')
    op.drop_index('ix_localstocks_ticker', table_name='localstocks')
    op.drop_table('localstocks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localstocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('ticker', sa.VARCHAR(), nullable=True),
    sa.Column('chart_link', sa.VARCHAR(), nullable=True),
    sa.Column('text_link', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('bhaiya_cmt', sa.TEXT(), nullable=True),
    sa.Column('xxx', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_localstocks_ticker', 'localstocks', ['ticker'], unique=False)
    op.create_index('ix_localstocks_name', 'localstocks', ['name'], unique=False)
    op.create_index('ix_localstocks_id', 'localstocks', ['id'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('species', sa.VARCHAR(), nullable=True),
    sa.Column('xxx', sa.VARCHAR(), nullable=True),
    sa.Column('yyy', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_animals_yyy', 'animals', ['yyy'], unique=False)
    op.create_index('ix_animals_xxx', 'animals', ['xxx'], unique=False)
    op.create_index('ix_animals_species', 'animals', ['species'], unique=False)
    op.create_index('ix_animals_name', 'animals', ['name'], unique=1)
    op.create_index('ix_animals_id', 'animals', ['id'], unique=False)
    # ### end Alembic commands ###
