"""remove supercoin

Revision ID: 4c4fb9cd6cde
Revises: 67f0243b8fe6
Create Date: 2025-05-06 00:33:44.688148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4fb9cd6cde'
down_revision: Union[str, None] = '67f0243b8fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'super_coins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('super_coins', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
