"""Initial migration

Revision ID: 50f9cfa58402
Revises: 640924edde91
Create Date: 2025-05-04 17:20:08.126942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f9cfa58402'
down_revision: Union[str, None] = '640924edde91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_localstocks_id', table_name='localstocks')
    op.drop_index('ix_localstocks_name', table_name='localstocks')
    op.drop_index('ix_localstocks_ticker', table_name='localstocks')
    op.drop_table('localstocks')
    op.drop_index('ix_animals_price', table_name='animals')
    op.drop_column('animals', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('price', sa.INTEGER(), nullable=True))
    op.create_index('ix_animals_price', 'animals', ['price'], unique=False)
    op.create_table('localstocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('ticker', sa.VARCHAR(), nullable=True),
    sa.Column('chart_link', sa.VARCHAR(), nullable=True),
    sa.Column('text_link', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('bhaiya_cmt', sa.TEXT(), nullable=True),
    sa.Column('xxx', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_localstocks_ticker', 'localstocks', ['ticker'], unique=False)
    op.create_index('ix_localstocks_name', 'localstocks', ['name'], unique=False)
    op.create_index('ix_localstocks_id', 'localstocks', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.VARCHAR(), nullable=False),
    sa.Column('receiver', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###
