"""Initial migration

Revision ID: 68c447878b3d
Revises: 704415c9fe35
Create Date: 2025-03-21 03:44:16.884567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c447878b3d'
down_revision: Union[str, None] = '704415c9fe35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('zzz', sa.String(), nullable=True))
    op.create_index(op.f('ix_animals_zzz'), 'animals', ['zzz'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_zzz'), table_name='animals')
    op.drop_column('animals', 'zzz')
    # ### end Alembic commands ###
