"""Add Animal model

Revision ID: 704415c9fe35
Revises: 48fe509d46fe
Create Date: 2025-03-21 03:43:44.634073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704415c9fe35'
down_revision: Union[str, None] = '48fe509d46fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('xxx', sa.String(), nullable=True),
    sa.Column('yyy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_index(op.f('ix_animals_name'), 'animals', ['name'], unique=True)
    op.create_index(op.f('ix_animals_species'), 'animals', ['species'], unique=False)
    op.create_index(op.f('ix_animals_xxx'), 'animals', ['xxx'], unique=False)
    op.create_index(op.f('ix_animals_yyy'), 'animals', ['yyy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_yyy'), table_name='animals')
    op.drop_index(op.f('ix_animals_xxx'), table_name='animals')
    op.drop_index(op.f('ix_animals_species'), table_name='animals')
    op.drop_index(op.f('ix_animals_name'), table_name='animals')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
