"""Add user_profile final

Revision ID: 714f36eea80f
Revises: 8dec94b00c99
Create Date: 2025-07-07 21:54:42.325958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714f36eea80f'
down_revision: Union[str, None] = '8dec94b00c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('gravatar_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=True),
    sa.Column('followers_url', sa.String(), nullable=True),
    sa.Column('following_url', sa.String(), nullable=True),
    sa.Column('gists_url', sa.String(), nullable=True),
    sa.Column('starred_url', sa.String(), nullable=True),
    sa.Column('subscriptions_url', sa.String(), nullable=True),
    sa.Column('organizations_url', sa.String(), nullable=True),
    sa.Column('repos_url', sa.String(), nullable=True),
    sa.Column('events_url', sa.String(), nullable=True),
    sa.Column('received_events_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('user_view_type', sa.String(), nullable=True),
    sa.Column('site_admin', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('blog', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hireable', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('twitter_username', sa.String(), nullable=True),
    sa.Column('notification_email', sa.String(), nullable=True),
    sa.Column('public_repos', sa.Integer(), nullable=True),
    sa.Column('public_gists', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('private_gists', sa.Integer(), nullable=True),
    sa.Column('total_private_repos', sa.Integer(), nullable=True),
    sa.Column('owned_private_repos', sa.Integer(), nullable=True),
    sa.Column('disk_usage', sa.Integer(), nullable=True),
    sa.Column('collaborators', sa.Integer(), nullable=True),
    sa.Column('two_factor_authentication', sa.Boolean(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_github_id'), 'user_profile', ['github_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_github_id'), table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
