"""animal price addedd

Revision ID: 9181a1522a2f
Revises: a4b40f4978d7
Create Date: 2025-03-23 15:39:54.284866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9181a1522a2f'
down_revision: Union[str, None] = 'a4b40f4978d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_animals_price'), 'animals', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_price'), table_name='animals')
    op.drop_column('animals', 'price')
    # ### end Alembic commands ###
