"""add super coin

Revision ID: a4b40f4978d7
Revises: 4d0dc39cfbb0
Create Date: 2025-03-21 22:40:59.898534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b40f4978d7'
down_revision: Union[str, None] = '4d0dc39cfbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('xxx', sa.String(), nullable=True),
    sa.Column('yyy', sa.String(), nullable=True),
    sa.Column('zzz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_index(op.f('ix_animals_name'), 'animals', ['name'], unique=True)
    op.create_index(op.f('ix_animals_species'), 'animals', ['species'], unique=False)
    op.create_index(op.f('ix_animals_xxx'), 'animals', ['xxx'], unique=False)
    op.create_index(op.f('ix_animals_yyy'), 'animals', ['yyy'], unique=False)
    op.create_index(op.f('ix_animals_zzz'), 'animals', ['zzz'], unique=False)
    op.add_column('user', sa.Column('super_coins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'super_coins')
    op.drop_index(op.f('ix_animals_zzz'), table_name='animals')
    op.drop_index(op.f('ix_animals_yyy'), table_name='animals')
    op.drop_index(op.f('ix_animals_xxx'), table_name='animals')
    op.drop_index(op.f('ix_animals_species'), table_name='animals')
    op.drop_index(op.f('ix_animals_name'), table_name='animals')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
