"""remove xxx yyy zzz

Revision ID: ccd562a06e05
Revises: 9181a1522a2f
Create Date: 2025-03-23 15:52:54.989337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd562a06e05'
down_revision: Union[str, None] = '9181a1522a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_animals_xxx', table_name='animals')
    op.drop_index('ix_animals_yyy', table_name='animals')
    op.drop_index('ix_animals_zzz', table_name='animals')
    op.drop_column('animals', 'zzz')
    op.drop_column('animals', 'yyy')
    op.drop_column('animals', 'xxx')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('xxx', sa.VARCHAR(), nullable=True))
    op.add_column('animals', sa.Column('yyy', sa.VARCHAR(), nullable=True))
    op.add_column('animals', sa.Column('zzz', sa.VARCHAR(), nullable=True))
    op.create_index('ix_animals_zzz', 'animals', ['zzz'], unique=False)
    op.create_index('ix_animals_yyy', 'animals', ['yyy'], unique=False)
    op.create_index('ix_animals_xxx', 'animals', ['xxx'], unique=False)
    # ### end Alembic commands ###
