"""add new model projects

Revision ID: ec99af3d93e6
Revises: 4c4fb9cd6cde
Create Date: 2025-05-21 15:44:46.242671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec99af3d93e6'
down_revision: Union[str, None] = '4c4fb9cd6cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
